export const REWARD_XP = {
  PLANT_CREATION: 50,
  VALID_WATERING: 25,
  SPECIES_DISCOVERY: 150,
  COMPLETION: 200,
};

export const LIFECYCLE_STAGES = {
  SEED: 'Seed',
  SPROUT: 'Sprout',
  GROWING: 'Growing Plant',
  FULLY_GROWN: 'Fully Grown Plant',
};

export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED',
  DUPLICATE_CARE_EVENT: 'DUPLICATE_CARE_EVENT',
};
